version: '3.5'

services:
  nest_postgres:
    container_name: nest_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: nest_test
      POSTGRES_PASSWORD: nest_test
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/var/www/nest-postgres/docker-volumes/postgress
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - nest_test
    restart: unless-stopped

  nest_pgadmin:
    container_name: nest_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_test@admin.com
      PGADMIN_DEFAULT_PASSWORD: nest_test
      PGADMIN_DEFAULT_SERVER_MODE: 'Fasle'
    volumes:
      - ./pgadmin:/var/www/nest-postgres/docker-volumes/pgadminn
    ports:
      - 127.0.0.1:5050:80
    networks:
      - nest_test
    restart: unless-stopped

networks:
  nest_test:
    driver: bridge

volumes:
  postres:
  pgadmin:
